theme: jekyll-theme-slate
port: 1985
markdown: kramdown
plugins:
  - jekyll-target-blank
  - jekyll-responsive-image
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 320
    - width: 480
    - width: 800